[workspace]
resolver = "2"
members = ["projects/*"]
default-members = [
    "projects/nyar-hir",
    "projects/nyar-vm",
    "projects/nyar-error",
    #    "projects/valkyrie-parser",
    "projects/nyar-lir",
]
exclude = [

]

[profile.release]
lto = true
opt-level = "s"